on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        "$NO" || { echo "::error::Must be merged in master"; exit 1 }
    - if: ${{ !cancelled() }}
      run: |
        "$NO" || { echo "::error::Must be merged in master"; exit 1 }
    - if: ${{ !cancelled() }}
      run: |
        "$NO" || { echo "::error::Must be merged in master"; exit 1 }
