on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo "- 1 :rocket:" >> $GITHUB_STEP_SUMMARY
    - run: |
        echo "- 2 :rocket:" >> $GITHUB_STEP_SUMMARY
    - run: |
        echo "- 3 :rocket:" >> $GITHUB_STEP_SUMMARY
