name: Check PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    branches:
      - staging

jobs:
  prcheck:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Test comment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "\
          Hey there! \
          What do you think? :suspect: \
          Best regards."
      
