name: Check PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    branches:
      - staging

jobs:
  prcheck:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Warning
        run: |
          title="My Custom Warning Title"
          message="Used to build and publish .NET source. Set up a specific version of the .NET and authentication to private NuGet repository"
          echo "::warning title=$title::$message"
          exit 1
      - name: Error
        if: ${{ !cancelled() }}
        run: |
          title="My Custom Error Title"
          message="Used to build and publish .NET source. Set up a specific version of the .NET and authentication to private NuGet repository"
          echo "::error title=$title::$message"
          exit 1
      - name: Notice
        if: ${{ !cancelled() }}
        run: |
          title="My Custom Notice Title"
          message="Used to build and publish .NET source. Set up a specific version of the .NET and authentication to private NuGet repository"
          echo "::notice title=$title::$message"
          exit 1
      - name: Debug
        if: ${{ !cancelled() }}
        run: |
          title="My Custom Debug Title"
          message="Used to build and publish .NET source. Set up a specific version of the .NET and authentication to private NuGet repository"
          echo "::debug title=$title::$message"
      - name: Summary
        if: ${{ !cancelled() }}
        run: |
          echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
      
