name: Sync
on:
  push:
    branches: [ "main", "staging" ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git User
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Sync Staging
        if: ${{ github.ref_name == 'main' }}
        run: |
          git checkout staging
          git merge --no-ff origin/main
          git push

      - name: Sync Dev
        run: |
          git checkout dev
          git merge --no-ff origin/staging
          git push
